### ISSUE TITLE
给我也整一个

### ISSUE THREAD

**Issue by chainsx** [FUjr/gdut_network#1]
如题

**Comment by FUjr** [comment]
luci/luci-app-gdutwifi/root/usr/share/gdutwifi/try_login.sh
可以自己改这个文件，前端就起穿参和现实作用呢

**Comment by chainsx** [comment]
大佬太强了

**Comment by chainsx** [comment]
> luci/luci-app-gdutwifi/root/usr/share/gdutwifi/try_login.sh 可以自己改这个文件，前端就起穿参和现实作用呢

不会呢

**Comment by FUjr** [comment]
你这样搞我要去你每个项目下面玩了

________________________________
